### PR TITLE
Changed set output

### PR DESCRIPTION
**Pull request by Ismoh**
I changed set output, based on https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ due to warnings of GitHubs actions log.

Please verify, if syntax is correct!

### CODE REVIEW

**Comment by Ismoh** [comment]
```
Resolves #92
https://api.github.com/repos/Ismoh/NoitaMP/pulls/97
Resolves 92
https://github.com/Ismoh/NoitaMP/issues/Resolves 92
Valid flag is: 0
::set-output name=valid::0
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by Ismoh** [comment]
@HarshCasper Please verify and take a look. Let me know, if there is anything need to be changed! Thanks!

**Comment by Ismoh** [comment]
In addition found out, that I did a mistake in the last PR.
issue_num isn't extracted correctly, because of changed pattern:
```
Resolves #92
https://api.github.com/repos/Ismoh/NoitaMP/pulls/97
Resolves 92 <----- THIS SHOULD BE 92
https://github.com/Ismoh/NoitaMP/issues/Resolves 92
Valid flag is: 0
::set-output name=valid::0
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
##[debug]steps.validator.outputs.valid='0'
```
Fixed it now within the latest commit.

**Comment by Ismoh** [comment]
I can improve this related to https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword !
Just give me a shout!

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
> I can improve this related to https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword ! Just give me a shout!

Thank You! Would be great if you can do it in a follow-up PR! I will cut out a release later today.

**Pull request merged**
