### PR TITLE
Updated pattern

### LINKED ISSUE #3: Missleading extracting of issue numbers
There is a pull request, which contains an issue number of another repository, because the changelog is shown as well.
Therefore `valid ==1` although there isnt any `Fixes #` or `Resolves #`.

https://github.com/Ismoh/NoitaMP/pull/83

Would be nice to improve that, otherwise my workflows aren't working.

Work around is to change dependabots comment, when there is an external issue tracked.

Workflow log in debug mode:
```
600db87</code></a> Compiled version 1.3.0</li>
<li><a href="https://github.com/HardNorth/github-version-generate/commit/42f7832228a9907b575077cf4a4f348d1993501f"><code>42f7832</code></a>
here ---> Merge pull request <a href="https://github-redirect.dependabot.com/HardNorth/github-version-generate/issues/39">#39</a> from HardNorth/develop</li>
<li><a href="https://github.com/HardNorth/github-version-
```
```
</details>
https://api.github.com/repos/Ismoh/NoitaMP/pulls/83
39
https://github.com/Ismoh/NoitaMP/issues/39
Valid flag is: 1
::set-output name=valid::1
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
```
Merge pull request <a href="https://github-redirect.dependabot.com/HardNorth/github-version-generate/issues/39">#39</a> from HardNorth/develop</li>
https://github.com/Ismoh/NoitaMP/issues/39
```

Would also be vise to consider the warning!

### PR DESCRIPTION
**Pull request by Ismoh**
Updated pattern for better searching for linked issues. Fixes #3

### CODE REVIEW

**Review by HarshCasper — APPROVED** [review]
Thanks a lot 🙏

**Comment by HarshCasper** [comment]
I will make a release by tomorrow 👍

**Comment by Ismoh** [comment]
Is there already a new release?

**Comment by Ismoh** [comment]
> Is there already a new release?

@HarshCasper ping

**Pull request merged**
